Repository jenkinsci/ssh-credentials-plugin, pull requests merged in 2024-03, with the labels that each got.

#157 Remove obsolete FindBugs configuration
  src/findbugs/excludesFilter.xml
Labels: chore

#197 Provide a default implementation of `SSHUserPrivateKey#getPrivateKey`
  src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/SSHUserPrivateKey.java
  src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/impl/BasicSSHUserPrivateKey.java
  src/test/java/com/cloudbees/jenkins/plugins/sshcredentials/impl/TrileadSSHPublicKeyAuthenticatorTest.java
Labels: developer

#199 Make trilead-api as optional as it contains some algo users may no want to use
  pom.xml
  src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/impl/TrileadSSHPasswordAuthenticator.java
  src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/impl/TrileadSSHPublicKeyAuthenticator.java
Labels: enhancement

#200 Remove usage of obsolete trilead-putty key
  src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/SSHUserPrivateKey.java
  src/main/java/com/cloudbees/jenkins/plugins/sshcredentials/impl/BasicSSHUserPrivateKey.java
Labels: removed
